import type { DossierData } from "../reportData";

export const sampleDossier: DossierData = {
  company: {
    id: "c1",
    name: "Acme Robotics",
    domain: "acme-robotics.com",
    industry: "Industrial Automation",
    created_at: "2026-01-01T00:00:00Z",
    last_processed_at: "2026-08-20T12:00:00Z",
    purchase_score: 72,
    final_decision: "qualified",
    disqualification_category: "not_disqualified",
    confidence: 0.81,
    coverage_percentage: 0.64,
  },
  pillars: [
    { score_type: "need", score: 80, confidence: 0.75, reasons: ["Hiring for ML roles", "Legacy tech stack detected"] },
    { score_type: "urgency", score: 60, confidence: 0.6, reasons: ["Recent funding round"] },
    { score_type: "capacity", score: 70, confidence: 0.7, reasons: ["Series B funded"] },
    { score_type: "digital_maturity", score: 55, confidence: 0.5, reasons: ["Modern cloud stack"] },
    { score_type: "org_readiness", score: 65, confidence: 0.65, reasons: ["Dedicated data team"] },
    { score_type: "winnability", score: 68, confidence: 0.6, reasons: ["No competing vendor found"] },
  ],
  purchaseScore: 72,
  purchaseConfidence: 0.81,
  recommendation: {
    executive_summary: "Acme Robotics shows strong buying signals.",
    fit_reasons: ["Need: Hiring for ML roles"],
    top_buying_signals: ["Hiring for ML roles", "Recent funding round"],
    top_risks: ["Weak Digital Maturity (55/100)"],
    suggested_approach: "Lead with the ML hiring angle.",
    contact_priority: "high",
    solution_match: null,
  },
  explanation: {
    company_domain: "acme-robotics.com",
    headline: "Strong fit — active hiring signals and recent funding.",
    evidence_coverage: {
      sources_discovered: 7,
      sources_attempted: 7,
      sources_successful: 5,
      sources_failed: 1,
      sources_zero_results: 1,
      sources_not_configured: 0,
      evidence_items_extracted: 12,
      evidence_items_accepted: 10,
      coverage_percentage: 0.64,
      collector_statuses: [
        { source: "jobs", status: "success", is_live: true, signal_count: 4, errors: [] },
        { source: "tech", status: "error", is_live: true, signal_count: 0, errors: ["builtwith: API Error"] },
      ],
      sources_not_implemented: [],
    },
    confidence_explanation: {
      overall_confidence: 0.81,
      level: "high",
      summary: "High confidence based on strong evidence coverage.",
      factors: [
        { name: "Evidence coverage", value: 0.64, weight: 0.4, description: "5 of 7 sources returned evidence." },
      ],
    },
    pillar_explanations: [],
    disqualification: {
      final_decision: "qualified",
      category: "not_disqualified",
      primary_reason: "Sufficient evidence supports a confident recommendation.",
      secondary_reasons: ["Strong hiring signal", "Recent funding event"],
      disqualifying_rules_triggered: [],
      supporting_evidence: [],
      missing_evidence: [],
      data_quality_limitations: [],
      confidence: 0.81,
      recommended_next_action: "Reach out to the VP Engineering.",
    },
    decision_intelligence: {
      recommendation: {
        priority: "high_priority",
        decision_score: 72,
        factors: [],
        rationale: "Strong evidence across need and capacity.",
        buying_intent: {
          level: "strong",
          score: 0.8,
          matched_signals: [
            { evidence_id: "e1", label: "ML hiring", excerpt: "Hiring 3 ML engineers", source: "Greenhouse", strength: "strong" },
          ],
          rationale: "Active hiring for exactly the roles this product serves.",
        },
        contradictions: {
          has_contradictions: true,
          findings: [
            {
              theme: "Vendor status",
              severity: "medium",
              description: "One source suggests an existing vendor, another suggests none.",
              evidence_a: { evidence_id: "e2", label: "No vendor found", excerpt: "No mention of existing tooling", source: "Website" },
              evidence_b: { evidence_id: "e3", label: "Vendor mention", excerpt: "Currently using CompetitorX", source: "News" },
            },
          ],
          summary: "One contradiction found regarding existing vendor status.",
        },
        why_now: {
          has_timing_trigger: true,
          data_sufficient: true,
          triggers: [
            {
              evidence_id: "e4",
              label: "Funding round",
              excerpt: "Raised $40M Series B",
              source: "News",
              trigger_type: "funding_event",
              published_at: "2026-08-01T00:00:00Z",
              freshness_label: "recent",
            },
          ],
          narrative: "A recent funding round suggests new budget availability.",
        },
      },
      change_analysis: {
        factors: [{ description: "Confirming vendor status would resolve the contradiction.", evidence_needed: ["Vendor confirmation"] }],
        summary: "Resolving the vendor contradiction would strengthen this recommendation.",
      },
      evidence_confidence: [],
      source_reliability: [],
    },
    sales_intelligence: {
      opportunity: { description: "Modernizing legacy ML infrastructure ahead of scale-up.", evidence_ids: ["e1"], confidence: 0.7 },
      solution_fit: { use_case: "ML Ops platform", fit_reasoning: "Matches their hiring profile.", evidence_ids: ["e1"], confidence: 0.7 },
      likely_buyer_roles: [{ role_title: "VP Engineering", rationale: "Owns the ML infrastructure budget.", evidence_ids: [] }],
      sales_trigger: {
        trigger_type: "funding_event",
        label: "Funding round",
        excerpt: "Raised $40M Series B",
        source: "News",
        evidence_id: "e4",
        freshness_label: "recent",
        narrative: "Reach out while budget is fresh.",
      },
      risks: [{ description: "Possible existing vendor relationship.", risk_type: "existing_vendor", evidence_ids: ["e3"] }],
      recommended_next_action: { action: "Schedule a discovery call with VP Engineering.", rationale: "They own the budget and are actively hiring for this.", evidence_ids: [] },
      evidence_ids: ["e1", "e2", "e3", "e4"],
      confidence: 0.7,
      data_sufficient: true,
    },
    generated_at: "2026-08-23T00:00:00Z",
  },
  evidence: [
    {
      id: "e1",
      signal_label: "ML hiring",
      excerpt: "Hiring 3 ML engineers",
      source: "Greenhouse",
      url: "https://boards.greenhouse.io/acme/jobs/1",
      confidence: 0.9,
      category: "ai_ml_hiring",
      collector: "jobs",
      pillar: "need",
      published_at: "2026-08-10T00:00:00Z",
      technology_name: null,
      technology_provider: null,
      job_title: "Machine Learning Engineer",
      job_department: "Engineering",
      job_location: "Remote",
      job_ats_provider: "greenhouse",
      job_posting_date: "2026-08-10T00:00:00Z",
      created_at: "2026-08-11T00:00:00Z",
    },
  ],
};
